### ISSUE TITLE
where is the book?

### ISSUE THREAD

**Issue by Sandy4321** [PacktPublishing/Applied-Machine-Learning-Explainability-Techniques#1]
where is the book?

**Comment by adib0073** [comment]
Thanks @Sandy4321 for reaching out and showing interest in the book. Its in progress and in the final phases of publication. :)
Fingers crossed and stay tuned for the book launch announcement!

**Comment by adib0073** [comment]
@Sandy4321 - I am happy to share that the book is ready to be launched on 29th July and is available for pre-order on Amazon -
Paperback version - https://amzn.to/3OTFFKc
Kindle version - https://amzn.to/3uuYuv0
Please feel free to reach out to me directly if you have any other question

**Comment by Sandy4321** [comment]
Is if possible to get pdf file ?

**Comment by adib0073** [comment]
@Sandy4321  - Yes, the pdf can be ordered through Amazon - https://amzn.to/3PRdonJ or from Packt - https://www.packtpub.com/product/applied-machine-learning-explainability-techniques/9781803246154
